# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

target 'MovieFlicks' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  # Pods for MovieFlicks
  pod 'AFNetworking'
  pod 'MBProgressHUD'

end
